#!/Users/youkim/Repo/PythonFromHell/pynorminette/.venv/bin/python
# -*- coding: utf-8 -*-

from sys import argv
from pynorminette_package import test

from typing import List
from termcolor import cprint
import pytest


def main(args: List[str]):
    test("mypy", args)
    test("black", args, flags=["--check"])


if __name__ == "__main__":
    if len(argv) <= 1:
        cprint("no files specified!", on_color="on_red")
        exit(1)

    main(argv[1:])
