#!/Users/youkim/Repo/PythonFromHell/pynorminette/.venv/bin/python
# -*- coding: utf-8 -*-

from sys import argv
from shutil import which
from subprocess import CalledProcessError, check_output, run, STDOUT

import pytest

from enum import IntEnum
from typing import List
from termcolor import cprint


class Status(IntEnum):
    OK = 0
    KO = 1


def test(name: str, args: List[str], *, flags: List[str] = []) -> Status:
    cprint(f"running: {name}", on_color="on_blue")
    _name = which(name)
    assert _name, f"no such path found for {name}"

    if run([_name] + flags + args).returncode:
        return Status.KO
    return Status.OK


def main(args: List[str]):
    test("mypy", args)
    test("black", args, flags=["--check"])


if __name__ == "__main__":
    if len(argv) <= 1:
        cprint("no files specified!", on_color="on_red")
        exit(1)

    main(argv[1:])
